### PR TITLE
function.hpp: Make empy Function constant initializable, remove IFNDR constexpr

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
- Considering that static variables aren't allowed in constexpr functions, the definition of `Vtable` for empty functor must be moved out from the function body.

- Todo: `empty_*` items are undocumented.

- `Function` can't be a literal type in C++17, so `constexpr` for some free functions is ill-formed, no diagnostic required, and should be removed.

### CODE REVIEW

**Comment by condy0919** [comment]
`empty_vtable_` is odr-used, so a definition is required.

**Comment by condy0919** [comment]
BTW, the non-diagnostic required errors are pains

**Comment by frederick-vs-ja** [comment]
Static constexpr member variable is already an inline variable, so the defintion already exists IMO. See also [ [dcl.constexpr]/1 ](https://timsong-cpp.github.io/cppwp/n4659/dcl.constexpr#1) (N4659 ver.).

Is there any compiler supporting C++17 inline variables but failing to compile the code?

**Comment by condy0919** [comment]
accepted

**Pull request merged**
